//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService.Models
{
  
    
    public partial class EmployeeTable
    {
        /// <summary>
        /// Gets or sets the unique identifier for the employee.
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// Gets or sets the name of the employee.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Gets or sets the email address of the employee.
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Gets or sets the gender of the employee.
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// Gets or sets the city where the employee is located.
        /// </summary>
        public string City { get; set; }
    }
}
